import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ['400', '500', '700']
});



export const metadata = {
  title: "Multi-step form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={ubuntu.className}
    >
      <body className="min-w-93.75 w-screen min-h-screen bg-[#EFF5FF] relative">
        <div
          className={`mx-auto h-[25vh] bg-[url("../public/images/bg-sidebar-mobile.svg")] bg-no-repeat bg-cover bg-center md:hidden`}
        ></div>
        {children}</body>
    </html>
  );
}
