import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ['400', '500', '700']
});



export const metadata = {
  title: "Multi-step form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={ubuntu.className}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
